"""Provider-neutral contracts for native application ownership persistence."""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Protocol


class NativeApplicationConflict(ValueError):
    """A stale writer or unresolved native resource prevents a transition."""


def utc_now() -> str:
    return datetime.now(UTC).isoformat(timespec="microseconds")


class NativeApplicationStore(Protocol):
    def register_session(self, record: dict) -> dict: ...
    def get_session(self, session_id: str) -> dict: ...
    def list_sessions(self) -> list[dict]: ...
    def update_session(self, session: dict, *, kind: str, trace_id: str) -> dict: ...
    def acquire_lease(self, lease: dict, *, expected_revision: int) -> dict: ...
    def get_lease(self, lease_id: str) -> dict: ...
    def transition_lease(
        self, lease_id: str, state: str, *, reason: str, trace_id: str
    ) -> None: ...
    def put_document(
        self, session_id: str, document: dict, *, trace_id: str
    ) -> None: ...
    def list_documents(self, session_id: str) -> list[dict]: ...
    def get_cleanup(self, session_id: str, cleanup_id: str) -> dict | None: ...
    def record_cleanup(self, receipt: dict) -> dict: ...
