#!/bin/bash
set -e

echo "=== Agent Container Starting ==="
echo "  LLM_API_URL : ${LLM_API_URL}"
echo "  Timestamp   : $(date -u)"

# ── 1. Validate LLM_API_URL ────────────────────────────────────────────────
if [ -z "${LLM_API_URL}" ]; then
  echo "Warning: LLM_API_URL environment variable is not set. Please configure it via the Setup Web UI." >&2
fi

# ── 2. Export CONTAINER_MANIFEST ────────────────────────────────────────────
if [ -f "/container-manifest.md" ]; then
  export CONTAINER_MANIFEST=$(cat /container-manifest.md)
else
  echo "Warning: /container-manifest.md is missing. CONTAINER_MANIFEST will be empty." >&2
  export CONTAINER_MANIFEST=""
fi

# ── 3. Create backup directories ───────────────────────────────────────────
mkdir -p /home/agent/.backups/etc || echo "Warning: Failed to create /home/agent/.backups/etc" >&2

# ── 4. Bootstrap Hermes Agent (first-run only) ─────────────────────────────
HERMES_HOME="/home/agent/.hermes"
export HERMES_HOME

if [ ! -d "${HERMES_HOME}" ]; then
  echo "First boot: initializing Hermes Agent..."

  # Create the directory structure hermes expects
  mkdir -p "${HERMES_HOME}/profiles/wright/sessions"
  mkdir -p "${HERMES_HOME}/profiles/wright/skills"
  mkdir -p "${HERMES_HOME}/webui/sessions"
  mkdir -p "${HERMES_HOME}/webui/workspace"

  # Write config.yaml in the format Hermes actually expects
  LLM_URL="${LLM_API_URL:-http://localhost:8000/v1}"
  LLM_KEY="${LLM_API_KEY:-NotNeeded}"
  LLM_MODEL="${LLM_API_MODEL:-default}"

  cat > "${HERMES_HOME}/config.yaml" <<YAML
# Hermes Agent configuration — auto-generated by Wright container entrypoint
model:
  base_url: ${LLM_URL}
  context_length: 131072
  default: ${LLM_MODEL}
  provider: custom
custom_providers:
- api_key: ${LLM_KEY}
  base_url: ${LLM_URL}
  model: ${LLM_MODEL}
  name: wright-llm
toolsets:
- hermes-cli
terminal:
  backend: local
  persistent_shell: true
  cwd: /home/agent/workspace
  timeout: 300
YAML

  # Copy config to wright profile as well
  cp "${HERMES_HOME}/config.yaml" "${HERMES_HOME}/profiles/wright/config.yaml"

  echo "Hermes bootstrapped with LLM endpoint: ${LLM_URL}"
else
  echo "Hermes home exists at ${HERMES_HOME}, skipping bootstrap."

  # Update LLM config if env vars changed (idempotent)
  if [ -n "${LLM_API_URL}" ] && [ -f "${HERMES_HOME}/config.yaml" ]; then
    CURRENT_URL=$(grep "^base_url:" "${HERMES_HOME}/config.yaml" 2>/dev/null | sed 's/base_url: *"\?\([^"]*\)"\?/\1/' || echo "")
    if [ "${CURRENT_URL}" != "${LLM_API_URL}" ]; then
      echo "Updating LLM endpoint from ${CURRENT_URL} to ${LLM_API_URL}"
      sed -i "s|^base_url:.*|base_url: \"${LLM_API_URL}\"|" "${HERMES_HOME}/config.yaml"
      if [ -f "${HERMES_HOME}/profiles/wright/config.yaml" ]; then
        sed -i "s|^base_url:.*|base_url: \"${LLM_API_URL}\"|" "${HERMES_HOME}/profiles/wright/config.yaml"
      fi
    fi
  fi
fi

# ── 5. Create default workspace directory ──────────────────────────────────
mkdir -p /home/agent/workspace

# ── 6. Log startup event ───────────────────────────────────────────────────
if echo "$(date -u) | Container started | LLM_API_URL=${LLM_API_URL}" >> /var/log/agent-startup.log 2>/dev/null; then
  : # Log succeeded
else
  echo "Warning: /var/log/agent-startup.log is not writable. Continuing without startup logging." >&2
fi

# ── 7. Start the requested command (typically supervisord) ─────────────────
echo "=== Starting services ==="
exec "$@"
