from __future__ import annotations

import os
import tempfile
import time
from pathlib import Path
from typing import Any

from workspace_service.workspace_path import WorkspacePath

from .runtime import WorkspaceManager


def _replace_generated_file(temporary: str, target: Path) -> None:
    # Windows readers that omit FILE_SHARE_DELETE can make atomic replacement
    # raise access denied (5), sharing violation (32), or lock violation (33).
    # Retry the same complete temporary file, never delete the existing target.
    # A real permission error can also be 5: it must still fail after this small
    # fixed budget. Other OS/disk/path errors propagate immediately.
    delays = (0.02, 0.04, 0.08, 0.16, 0.20)
    for attempt in range(len(delays) + 1):
        try:
            os.replace(temporary, target)
            return
        except OSError as error:
            if getattr(error, "winerror", None) not in {5, 32, 33} or attempt == len(
                delays
            ):
                raise
            time.sleep(delays[attempt])


class LocalWorkspaceFiles:
    def __init__(self, workspace_dir: str) -> None:
        self.workspace_dir = workspace_dir
        self.manager = WorkspaceManager(workspace_dir)

    def tree(self) -> dict[str, Any]:
        return self.manager.get_workspace_tree()

    def read(
        self, relative_path: str, backup_id: str | None = None
    ) -> tuple[Path, bytes]:
        if backup_id:
            absolute = WorkspacePath(self.workspace_dir).backup(
                backup_id, must_exist=True
            )
            return absolute, absolute.read_bytes()
        absolute = Path(self.manager.sanitize_path(relative_path))
        if not absolute.is_file():
            raise FileNotFoundError(relative_path)
        return absolute, self.manager.read_file_content(relative_path)

    def create(self, path: str, node_type: str) -> dict[str, Any]:
        return self.manager.create_file_node(path, node_type)

    def delete(self, path: str) -> None:
        self.manager.delete_file_node(path)

    def move(self, source: str, destination: str) -> None:
        self.manager.move_file_node(source, destination)

    def write(self, path: str, content: bytes) -> None:
        self.manager.write_file_content(path, content)

    def write_generated(self, path: str, content: bytes, policy: str) -> str:
        """Publish complete generated bytes, reserving indexed names atomically."""
        if policy not in {"indexed", "overwrite"}:
            raise ValueError("Unknown output file policy")
        paths = WorkspacePath(self.workspace_dir)
        target = paths.resolve(path)
        target.parent.mkdir(parents=True, exist_ok=True)
        target = paths.resolve(path)
        fd, temporary = tempfile.mkstemp(prefix=".wright-output-", dir=target.parent)
        try:
            with os.fdopen(fd, "wb") as stream:
                stream.write(content)
                stream.flush()
                os.fsync(stream.fileno())
            if policy == "overwrite":
                _replace_generated_file(temporary, target)
                return target.relative_to(paths.root).as_posix()
            for index in range(100_000):
                candidate = (
                    target
                    if index == 0
                    else target.with_name(f"{target.stem}-{index:03d}{target.suffix}")
                )
                relative = candidate.relative_to(paths.root).as_posix()
                candidate = paths.resolve(relative)
                try:
                    # A hard link publishes complete bytes and fails if a concurrent
                    # writer has already taken this name. Never expose an empty file.
                    os.link(temporary, candidate)
                    return relative
                except FileExistsError:
                    continue
            raise FileExistsError("No unused output index is available")
        finally:
            if os.path.exists(temporary):
                os.unlink(temporary)

    def backup(self, path: str, content: bytes) -> str:
        return self.manager.write_backup(path, content)

    def delete_backup(self, backup_id: str) -> None:
        self.manager.delete_backup(backup_id)
