from __future__ import annotations

import argparse
from pathlib import Path

OUTPUT = Path("apps/web/src/types/generated/wright-contracts.ts")


def render_contracts() -> str:
    return """// Generated by scripts/generate-frontend-contracts.py. Do not edit by hand.
// Source models: tool_registry.safety, tool_registry.validation_evidence,
// agent_adapters.registry, workspace_service.models.

export type McpPolicyOperation = "install" | "start" | "call";

export interface McpPolicyDecision {
  allowed: boolean;
  operation: McpPolicyOperation;
  reason: string;
  required_approvals: string[];
  missing_credentials: string[];
  network_required: boolean;
  blocked_by_catalog: boolean;
  diagnostics: Record<string, unknown>;
}

export interface ValidationStepEvidence {
  name: string;
  status: string;
  output: string;
  error: string | null;
  duration_ms: number | null;
}

export interface ValidationEvidence {
  server_id: string;
  catalog_version: string;
  validation_started_at: string | null;
  validation_finished_at: string | null;
  environment: string;
  container_image: string | null;
  install_steps: string[];
  protocol_probes: ValidationStepEvidence[];
  safe_backend_probe: ValidationStepEvidence | null;
  gateway_proxy_probe: ValidationStepEvidence[];
  credential_requirements: string[];
  network_requirements: Record<string, unknown>;
  result: string | null;
  status: string;
  steps: ValidationStepEvidence[];
  diagnostics: string;
  missing_dependencies: string[];
  follow_up_url: string | null;
  follow_up_required: boolean;
  redactions: string[];
}

export type AgentSupportLevel =
  | "supported"
  | "experimental"
  | "stub"
  | "unavailable";

export interface AgentRuntimeProviderContract {
  name: string;
  display_name: string;
  description: string;
  supported: boolean;
  support_level: AgentSupportLevel;
  is_default: boolean;
}

export interface ContextMaterializationResult {
  provider_id: string;
  support_level: AgentSupportLevel;
  files_written: string[];
  warnings: string[];
  error_code: string | null;
}

export interface WorkspaceRecord {
  workspace_id: string;
  session_id: string;
  workspace_name: string | null;
  local_path: string;
  updated_at: number;
  git_remote_url: string | null;
  git_username: string | null;
  enabled_tools: string[] | null;
}

export interface WorkspaceActivation {
  success: boolean;
  session_id: string;
  workspace_path: string;
  context: ContextMaterializationResult;
}

export interface FileExecutionResult {
  success: boolean;
  stdout: string;
  stderr: string;
  exit_code: number;
}
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    rendered = render_contracts()

    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            print(
                f"{OUTPUT} is out of date. Run scripts/generate-frontend-contracts.py"
            )
            return 1
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"Wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
