import type { NativeMilestone } from "../components/program-status/NativeMilestone.types";

export function makeNativeMilestone(): NativeMilestone {
  return {
    id: "NATIVE-01",
    title: "Native engineering process: create to verified output",
    feature_id: "EPP-N01",
    scope_revision: 1,
    scope_history: [
      {
        revision: 1,
        observed_at: "2026-09-04T12:00:00Z",
        added_task_ids: ["T001", "T002", "T003", "T004"],
        removed_task_ids: [],
        reason: "Initial bounded milestone",
      },
    ],
    source_commit: "c".repeat(40),
    observed_at: "2026-09-04T14:00:00Z",
    candidate_commit: "b".repeat(40),
    language_authority:
      "The Wright native language is authoritative for AI clients, canvas and runtime.",
    tasks: [
      {
        id: "T001",
        title: "Define the shared contract",
        activity: "idle",
        owner: "model",
        implemented: true,
        verification: "passed",
        integration: "integrated",
        integration_required: true,
        blocker_ids: [],
      },
      {
        id: "T002",
        title: "Implement the editor",
        activity: "active",
        owner: "editor",
        implemented: true,
        verification: "stale",
        integration: "pending",
        integration_required: true,
        blocker_ids: [],
      },
      {
        id: "T003",
        title: "Observe human usability",
        activity: "blocked",
        owner: "coordinator",
        implemented: false,
        verification: "not_tested",
        integration: "pending",
        integration_required: true,
        blocker_ids: ["B-HUMAN"],
      },
      {
        id: "T004",
        title: "Record final deployment",
        activity: "planned",
        owner: "coordinator",
        implemented: false,
        verification: "not_tested",
        integration: "not_applicable",
        integration_required: false,
        blocker_ids: [],
      },
    ],
    counts: {
      implementation: { completed: 2, total: 4 },
      verification: { completed: 1, total: 4 },
      integration: { completed: 1, total: 3, not_applicable: 1 },
    },
    acceptance: [
      {
        id: "AC01",
        title: "Shared process contract",
        task_ids: ["T001"],
        check_ids: ["Q-MODEL"],
        status: "passed",
        missing_check_ids: [],
      },
      {
        id: "AC02",
        title: "Accessible authoring and human review",
        task_ids: ["T002", "T003"],
        check_ids: ["Q-EDITOR", "Q-HUMAN"],
        status: "pending",
        missing_check_ids: ["Q-EDITOR", "Q-HUMAN"],
      },
    ],
    checks: [
      {
        id: "Q-MODEL",
        label: "Shared model invariants",
        stage: "verification",
        kind: "automated_test",
        task_ids: ["T001"],
        status: "passed",
        evidence_id: "EV-MODEL",
        observed_at: "2026-09-04T13:00:00Z",
        tested_commit: "a".repeat(40),
        coverage_current: true,
        counts: { total: 12, passed: 12, failed: 0, skipped: 0, not_run: 0 },
        summary: "Valid and invalid document cases passed.",
        artifact_urls: [
          `https://github.com/burhop/wright/blob/${"a".repeat(40)}/evidence/model.json`,
        ],
      },
      {
        id: "Q-EDITOR",
        label: "Editor browser journey",
        stage: "verification",
        kind: "automated_test",
        task_ids: ["T002"],
        status: "stale",
        evidence_id: "EV-EDITOR",
        observed_at: "2026-09-04T13:30:00Z",
        tested_commit: "a".repeat(40),
        coverage_current: false,
        counts: { total: 8, passed: 4, failed: 1, skipped: 2, not_run: 1 },
        summary: "Recovery failed on the previous source scope.",
        artifact_urls: [],
      },
      {
        id: "Q-HUMAN",
        label: "Engineer usability sessions",
        stage: "verification",
        kind: "human_review",
        task_ids: ["T003"],
        status: "not_tested",
        evidence_id: null,
        observed_at: null,
        tested_commit: null,
        coverage_current: null,
        counts: null,
        summary: "Participant sessions have not been completed.",
        artifact_urls: [],
      },
    ],
    blockers: [
      {
        id: "B-HUMAN",
        summary: "Human usability evidence pending",
        owner: "coordinator",
        required_action: "Arrange and record participant sessions",
        task_ids: ["T003"],
        check_ids: ["Q-HUMAN"],
        observed_at: "2026-09-04T14:00:00Z",
      },
    ],
    next_task_ids: ["T002", "T003"],
    examples: [
      {
        id: "EX-01",
        title: "Calculation with units",
        execution_mode: "local_computation",
        maturity: "verified",
        check_ids: ["Q-MODEL"],
        definition_path: "examples/calculation.json",
      },
      {
        id: "EX-02",
        title: "Tool artifact review",
        execution_mode: "live_mcp",
        maturity: "not_tested",
        check_ids: ["Q-EDITOR"],
        definition_path: "examples/tool.json",
      },
      {
        id: "EX-03",
        title: "Document review fixture",
        execution_mode: "fixture",
        maturity: "defined",
        check_ids: [],
        definition_path: "examples/fixture.json",
      },
    ],
    delivery: {
      branch: "codex/079-native-process-milestone",
      target_branch: "dev",
      baseline_commit: "9".repeat(40),
      candidate_commit: "b".repeat(40),
      pull_requests: [
        {
          url: "https://github.com/burhop/wright/pull/123",
          head_commit: "b".repeat(40),
          observed_at: "2026-09-04T14:00:00Z",
        },
      ],
      merged_commit: null,
      deployment_status: "not_verified",
      deployment_check_ids: [],
    },
    readiness: {
      native_milestone: "in_progress",
      benchmark: "not_qualified",
      commercial: "not_assessed",
      release: "not_eligible",
      rivet_migration: "future_work",
      rivet_retirement: "future_work",
    },
    capabilities: ["Inspect the validated native definition"],
  };
}
