name: dependency review

on:
  pull_request:
    branches: [main, dev]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Review dependency changes
        uses: actions/dependency-review-action@1ad29ea4a422cce9a242a9fae469541dcd08addc # v4
        with:
          fail-on-severity: high
          deny-licenses: GPL-3.0, AGPL-3.0
