name: frontend-quality

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  frontend-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint with ESLint
        run: npx -w apps/web eslint .

      - name: Check Formatting with Prettier
        run: npx prettier --check apps/web/

      - name: Type Check with TSC
        run: npx tsc --noEmit -p apps/web/tsconfig.app.json
